boot-repair needs a PPA - adding documentation code
If boot-repair is available somehow, it will be installed.
However, that is not common.  Yet, we don't want to prompt
the user in the middle of remastersys for anything, so
we can't easily add a PPA.

Not sure how to best handle this, so the code to add the PPA
is all there, but commented out.  In our case, we use
wasta-offline, so boot-repair is always available...

diff --git a/usr/bin/wasta-remastersys b/usr/bin/wasta-remastersys
--- a/usr/bin/wasta-remastersys
+++ b/usr/bin/wasta-remastersys
@@ -297,6 +297,25 @@ cdfs (){
         log_msg "Adding Boot-Repair to LiveCD"
         REMOVE_BOOT_REPAIR=YES
         apt-get -y -q install boot-repair &> /dev/null
+#Commenting this section out because the user should not be prompted in
+#the middle of remastersys, and shouldn't add PPAs automatically.
+#boot-repair will silently fail to install if the package hasn't been made
+#available from some trusted source.
+#        KEYPRESS=Y
+#        until [ -x /usr/bin/boot-repair ] || [ "${KEYPRESS^^}" == "N" ]; do
+#            read -p "Add boot-repair PPA for LiveCD?  (Y/n)  "  KEYPRESS
+#            if [ "${KEYPRESS^^}" != "N" ]; then
+#                add-apt-repository --yes ppa:yannubuntu/boot-repair
+#                apt-get update
+#                apt-get --quiet install --yes boot-repair
+#                add-apt-repository --remove --yes ppa:yannubuntu/boot-repair
+#                #Mint's hack of add-apt-repository doesn't support --remove
+#                if [[ $? != 0 ]]; then
+#                    log_msg "NOTICE: boot-repair PPA forcibly removed."
+#                    rm -f /etc/apt/sources.list.d/yannubuntu-boot-repair-*.list
+#                fi
+#            fi
+#        done
     fi
 
     #Installing chntpw if not already installed
